spring.application.name=task_manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=task_manager_dev
spring.datasource.password=task_manager123

# Cria/atualiza as tabelas automaticamente (só em dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html